insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (1, 'Saab', '9-3', 2004, 'Diesel', 'F', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (2, 'Mazda', 'Mazdaspeed 3', 2011, 'Gasoline', 'D', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (3, 'Toyota', 'Avalon', 2006, 'Natural Gas', 'D', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (4, 'Plymouth', 'Breeze', 2000, 'Hybrid', 'E', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (5, 'Ford', 'E-Series', 1963, 'Electric', 'D', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (6, 'Honda', 'Accord', 1989, 'Gasoline', 'A', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (7, 'Nissan', 'NV2500', 2012, 'Diesel', 'B', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (8, 'Hyundai', 'Elantra', 2008, 'Electric', 'C', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (9, 'Subaru', 'Impreza', 1998, 'Gasoline', 'B', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (10, 'Pontiac', 'Grand Prix', 1977, 'Natural Gas', 'E', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (11, 'Mercedes-Benz', 'W201', 1992, 'Gasoline', 'C', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (12, 'GMC', 'Savana 3500', 2010, 'Gasoline', 'A', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (13, 'Daewoo', 'Lanos', 2002, 'Gasoline', 'C', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (14, 'Saturn', 'Outlook', 2009, 'Gasoline', 'B', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (15, 'GMC', 'Yukon XL', 2006, 'Electric', 'B', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (16, 'Chevrolet', 'G-Series G30', 1992, 'Natural Gas', 'C', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (17, 'Dodge', 'Dakota Club', 2007, 'Diesel', 'C', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (18, 'Infiniti', 'FX', 2003, 'Hybrid', 'C', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (19, 'Mercedes-Benz', 'Sprinter', 2011, 'Gasoline', 'A', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (20, 'Pontiac', 'Sunfire', 2004, 'Diesel', 'E', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (21, 'Acura', 'RDX', 2007, 'Natural Gas', 'F', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (22, 'Suzuki', 'Swift', 2000, 'Hybrid', 'E', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (23, 'Buick', 'LeSabre', 1986, 'Hybrid', 'E', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (24, 'Toyota', 'Supra', 1993, 'Hybrid', 'F', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (25, 'Toyota', 'Corolla', 2007, 'Hybrid', 'B', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (26, 'Honda', 'Accord', 1987, 'Electric', 'E', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (27, 'GMC', 'Yukon XL 1500', 2007, 'Hybrid', 'D', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (28, 'Dodge', 'Ram 3500', 2002, 'Natural Gas', 'E', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (29, 'MINI', 'Cooper Clubman', 2011, 'Gasoline', 'E', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (30, 'Volkswagen', 'Rabbit', 2006, 'Electric', 'E', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (31, 'GMC', '1500 Club Coupe', 1994, 'Natural Gas', 'C', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (32, 'Ford', 'E350', 2006, 'Electric', 'D', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (33, 'Chevrolet', 'Suburban 2500', 1999, 'Natural Gas', 'F', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (34, 'Toyota', 'Highlander', 2005, 'Gasoline', 'B', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (35, 'Toyota', 'Previa', 1994, 'Gasoline', 'F', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (36, 'Hyundai', 'Excel', 1993, 'Electric', 'D', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (37, 'Jaguar', 'XK', 2007, 'Gasoline', 'E', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (38, 'Chevrolet', 'Express 2500', 2011, 'Natural Gas', 'A', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (39, 'Mazda', 'Familia', 1989, 'Diesel', 'C', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (40, 'Audi', 'TT', 2009, 'Diesel', 'E', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (41, 'Dodge', 'Charger', 2010, 'Diesel', 'E', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (42, 'Mitsubishi', 'Cordia', 1985, 'Natural Gas', 'F', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (43, 'Dodge', 'Viper', 2006, 'Natural Gas', 'B', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (44, 'Subaru', 'Leone', 1989, 'Gasoline', 'C', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (45, 'Mercedes-Benz', 'S-Class', 2004, 'Natural Gas', 'D', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (46, 'GMC', 'Rally Wagon 1500', 1993, 'Electric', 'D', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (47, 'Lamborghini', 'Murciélago', 2006, 'Gasoline', 'C', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (48, 'Toyota', 'Land Cruiser', 2003, 'Diesel', 'F', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (49, 'Ford', 'Mustang', 1964, 'Natural Gas', 'B', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (50, 'Toyota', 'Land Cruiser', 1992, 'Gasoline', 'E', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (51, 'Nissan', 'Pathfinder', 2002, 'Diesel', 'F', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (52, 'Dodge', 'Ram Wagon B350', 1993, 'Hybrid', 'B', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (53, 'Kia', 'Spectra', 2006, 'Hybrid', 'C', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (54, 'Pontiac', 'G5', 2008, 'Gasoline', 'F', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (55, 'Land Rover', 'Range Rover', 2010, 'Electric', 'D', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (56, 'Honda', 'Element', 2007, 'Gasoline', 'F', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (57, 'Lincoln', 'Continental', 1988, 'Natural Gas', 'B', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (58, 'Mitsubishi', 'Pajero', 1985, 'Diesel', 'E', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (59, 'Dodge', 'Ram', 1994, 'Gasoline', 'D', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (60, 'Kia', 'Sportage', 2005, 'Diesel', 'F', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (61, 'Toyota', 'T100', 1996, 'Natural Gas', 'E', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (62, 'Honda', 'Civic', 1999, 'Natural Gas', 'D', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (63, 'Kia', 'Mentor', 1997, 'Gasoline', 'A', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (64, 'Ford', 'Econoline E350', 1992, 'Electric', 'E', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (65, 'Chrysler', 'Crossfire Roadster', 2006, 'Natural Gas', 'F', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (66, 'Nissan', 'Quest', 2004, 'Hybrid', 'F', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (67, 'Cadillac', 'Escalade ESV', 2003, 'Natural Gas', 'B', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (68, 'Kia', 'Rondo', 2010, 'Natural Gas', 'C', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (69, 'Pontiac', 'Sunbird', 1987, 'Gasoline', 'A', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (70, 'Spyker', 'C8', 2007, 'Electric', 'C', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (71, 'BMW', '3 Series', 1997, 'Electric', 'F', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (72, 'Ford', 'Aerostar', 1997, 'Gasoline', 'C', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (73, 'Plymouth', 'Voyager', 1992, 'Electric', 'C', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (74, 'Mercury', 'Grand Marquis', 1985, 'Electric', 'E', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (75, 'Pontiac', 'Sunbird', 1990, 'Hybrid', 'B', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (76, 'Dodge', 'Magnum', 2006, 'Gasoline', 'C', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (77, 'Rolls-Royce', 'Phantom', 2011, 'Natural Gas', 'C', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (78, 'Chevrolet', 'Venture', 1998, 'Electric', 'D', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (79, 'Acura', 'TSX', 2010, 'Hybrid', 'F', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (80, 'Dodge', 'Durango', 2001, 'Electric', 'A', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (81, 'Mitsubishi', 'Eclipse', 2009, 'Electric', 'A', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (82, 'Mercedes-Benz', 'S-Class', 2006, 'Diesel', 'C', 'G');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (83, 'Bentley', 'Arnage', 2005, 'Gasoline', 'C', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (84, 'BMW', 'M', 2000, 'Hybrid', 'D', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (85, 'Dodge', 'Neon', 2001, 'Diesel', 'D', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (86, 'Hyundai', 'Santa Fe', 2001, 'Hybrid', 'A', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (87, 'Ford', 'Freestar', 2006, 'Diesel', 'F', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (88, 'Dodge', 'Ram Van B150', 1992, 'Electric', 'D', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (89, 'Volvo', 'V50', 2008, 'Gasoline', 'A', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (90, 'Porsche', '924', 1988, 'Electric', 'F', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (91, 'Volkswagen', 'Jetta', 1995, 'Diesel', 'D', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (92, 'Mazda', 'Familia', 1988, 'Electric', 'E', 'F');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (93, 'Hyundai', 'Santa Fe', 2003, 'Hybrid', 'B', 'A');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (94, 'Honda', 'CR-V', 2011, 'Diesel', 'E', 'D');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (95, 'Volvo', 'C70', 2002, 'Diesel', 'E', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (96, 'Hummer', 'H1', 2006, 'Hybrid', 'B', 'E');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (97, 'Mitsubishi', 'Lancer', 2005, 'Hybrid', 'F', 'C');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (98, 'Kia', 'Sportage', 2000, 'Natural Gas', 'A', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (99, 'Pontiac', 'Sunbird', 1994, 'Gasoline', 'C', 'B');
insert into "Spatial_US_Mapping"."US_State_Vehicle" (vehicle_id, make, model, year, fuel_type, safety_rating, emissions_rating) values (100, 'Porsche', 'Cayenne', 2011, 'Natural Gas', 'E', 'E');
